import '../node_modules/normalize.css/normalize.css';
import './menu-style.css';
import Burger from './burger.jpg';
import ChickenTenders from './chickenTenderPlatter.jpg';
import Chili from './chili.jpg';
import FishChips from './fishAndChips.jpg';
import FriedShrimp from './friedShrimpPlatter.jpg';
import GatorNuggets from './gatorNuggets.jpeg';
import GatorStew from './gatorStew.jpg';
import Ribs from './ribs.jpg';
import ShrimpGumbo from './shrimpGumbo.jpg'
export default function createMenuPage(){
    const content = document.querySelector('#content');
    content.classList.remove('content-contact');
    const title = document.createElement('p');
    title.classList.add('menu-title');
    title.textContent = "Menu";
    const platterSect = document.createElement('p');
    const platterSide = document.createElement('p');
    const soupSect = document.createElement('p');
    const soupSide = document.createElement('p');
    platterSect.textContent = "Platters"
    platterSide.textContent = "*All platters are served with a side of french fries";
    soupSect.textContent = 'Soups and stews';
    soupSide.textContent = '*All soups are served with a side salad and bread';
    platterSect.classList.add('section-head');
    soupSect.classList.add('section-head');
    platterSide.classList.add('side');
    soupSide.classList.add('side');
    const burgerContainer = document.createElement('div');
    const gatorNuggetsContainer = document.createElement('div');
    const gatorStewContainer = document.createElement('div');
    const chiliContainer = document.createElement('div');
    const tenderPlatterContainer = document.createElement('div');
    const ribsContainer = document.createElement('div');
    const shrimpGumboContainer = document.createElement('div');
    const fishChipsContainer = document.createElement('div');
    const friedShrimpContainer = document.createElement('div');
    let containers = [burgerContainer, gatorNuggetsContainer, gatorStewContainer, chiliContainer, tenderPlatterContainer, ribsContainer, shrimpGumboContainer, fishChipsContainer, friedShrimpContainer];
    containers.forEach(container => container.classList.add('menu-item'));
    const burgerImg = document.createElement('img');
    burgerImg.src = Burger;
    const gatorNuggetsImg = document.createElement('img');
    gatorNuggetsImg.src = GatorNuggets;
    const gatorStewImg = document.createElement('img');
    gatorStewImg.src = GatorStew;
    const chiliImg = document.createElement('img');
    chiliImg.src = Chili;
    const tenderPlatterImg = document.createElement('img');
    tenderPlatterImg.src = ChickenTenders;
    const ribsImg = document.createElement('img');
    ribsImg.src = Ribs;
    const shrimpGumboImg = document.createElement('img');
    shrimpGumboImg.src = ShrimpGumbo;
    const fishChipsImg = document.createElement('img');
    fishChipsImg.src = FishChips;
    const friedShrimpImg = document.createElement('img');
    friedShrimpImg.src = FriedShrimp;
    const burgerName = document.createElement('p');
    burgerName.textContent = "Cheeseburger";
    const friedShrimpName = document.createElement('p');
    friedShrimpName.textContent = "Fried shrimp";
    const fishChipsName = document.createElement('p');
    fishChipsName.textContent = "Fish and chips";
    const gatorNuggetsName = document.createElement('p');
    gatorNuggetsName.textContent = "Gator nuggets";
    const tenderPlatterName = document.createElement('p');
    tenderPlatterName.textContent = "Chicken tender platter";
    const ribsName = document.createElement('p');
    ribsName.textContent = "Ribs";
    const shrimpGumboName = document.createElement('p');
    shrimpGumboName.textContent = "Cajun shrimp gumbo";
    const gatorStewName = document.createElement('p');
    gatorStewName.textContent = "Gator stew";
    const chiliName = document.createElement('p');
    chiliName.textContent = "Spicy beef chili";
    const names = [burgerName, friedShrimpName, fishChipsName, gatorNuggetsName, tenderPlatterName, ribsName, shrimpGumboName, gatorStewName, chiliName];
    names.forEach(name => name.classList.add('item-name'));
    const burgerDescription = document.createElement('p');
    burgerDescription.textContent = "Juicy 1/2 pound angus burger cooked to perfection. Cooked to order. Best burger you've ever had!";
    const friedShrimpDescription = document.createElement('p');
    friedShrimpDescription.textContent = "Delectable and fresh fried shrimp. Served in a beer batter; comes either regular or cajun. We get our shrimp fresh daily!";
    const fishChipsDescription = document.createElement('p');
    fishChipsDescription.textContent = "A classic plate of fish and chips. Our fresh cod is tossed in a beer batter and seasoned with our secret spice mix. Served with tartar sauce.";
    const gatorNuggetsDescription = document.createElement('p');
    gatorNuggetsDescription.textContent = "Our signature gator nuggets! This is our most popular item, and for good reason! Take a bite of the swamp with these savory gator bites. Tastes like chicken!";
    const tenderPlatterDescription = document.createElement('p');
    tenderPlatterDescription.textContent = "A chicken tender platter. Chicken tenders fried to golden perfection, served with a sauce of your choosing.";
    const ribsDescription = document.createElement('p');
    ribsDescription.textContent = "Our ribs are served with barbeque sauce and a whole lotta flavor! The meat practically drips off the bone as we slow cook these for hours to guarentee the most tender meat for our customers!";
    const shrimpGumboDescription = document.createElement('p');
    shrimpGumboDescription.textContent = "Cajun shrimp gumbo, Louisiana style! Served with a bit of kick in the pot, this gumbo comes with the freshest shrimp and juicy sausage. Will leave your mouth watering.";
    const gatorStewDescription = document.createElement('p');
    gatorStewDescription.textContent = "Gator stew! We like to say our gator stew is a taste of the swamplands itself, with our juicy gator meat, vegetable medley, and of course our secret spices! Nothing says 'I'm in the the swamp' quite like taking a swig of it!";
    const chiliDescription = document.createElement('p');
    chiliDescription.textContent = "Our spicy beef chili has won the 'Southwest Florida Grand Chili Chamionship' two years in a row now! We take great pride in our chili, made with Gramma's famous home recipe. Made with the best ingredients and lots of love!";
    const descriptions = [burgerDescription, friedShrimpDescription, fishChipsDescription, gatorNuggetsDescription, tenderPlatterDescription, ribsDescription, shrimpGumboDescription, gatorStewDescription, chiliDescription];
    descriptions.forEach(description => description.classList.add('description'));
    chiliContainer.append(chiliImg, chiliName, chiliDescription);
    burgerContainer.append(burgerImg, burgerName, burgerDescription);
    gatorNuggetsContainer.append(gatorNuggetsImg, gatorNuggetsName, gatorNuggetsDescription);
    gatorStewContainer.append(gatorStewImg, gatorStewName, gatorStewDescription);
    tenderPlatterContainer.append(tenderPlatterImg, tenderPlatterName, tenderPlatterDescription);
    ribsContainer.append(ribsImg, ribsName, ribsDescription);
    fishChipsContainer.append(fishChipsImg, fishChipsName, fishChipsDescription);
    shrimpGumboContainer.append(shrimpGumboImg, shrimpGumboName, shrimpGumboDescription);
    friedShrimpContainer.append(friedShrimpImg, friedShrimpName, friedShrimpDescription);
    content.append(title, platterSect, platterSide, burgerContainer, friedShrimpContainer, fishChipsContainer, gatorNuggetsContainer, tenderPlatterContainer, ribsContainer, soupSect, soupSide, shrimpGumboContainer, gatorStewContainer, chiliContainer);
}
